### PR TITLE
Raise exception if Auth0 response status is bad (plus proper logging)

### PR DESCRIPTION
**Pull request by xoen**
### What
This PR tweaks the `API.request()` method to check the response status code and raise an exception early on when not a `2xx`. This is done using `request`'s [`#raise_for_status()`](https://requests.readthedocs.io/en/master/user/quickstart/#response-status-codes) method.

This PR also adds some logging using the [`structlog` module](http://www.structlog.org/en/stable/) - thanks to @ntoll for the logging 🏆 .

### Why
Few users got the following error when trying to deploy their Webapp:

```python
[...]
Creating view:app permission ...
Traceback (most recent call last):
  File "/opt/resource/out", line 80, in <module>
    create_client()
  File "/usr/local/lib/python3.7/site-packages/moj_analytics/concourse.py", line 25, in __call__
    response = self.fn(*self.args, **self.kwargs)
  File "/opt/resource/out", line 61, in create_client
    Permission(name='view:app', applicationId=client_id))
  File "/usr/local/lib/python3.7/site-packages/moj_analytics/auth0_client.py", line 123, in get_or_create
    result = self.create(resource)
  File "/usr/local/lib/python3.7/site-packages/moj_analytics/auth0_client.py", line 87, in create
    raise CreateResourceError(response)
moj_analytics.auth0_client.CreateResourceError: {'statusCode': 400, 'error': 'Bad Request', 'message': 'Permission with name "view:app" already exists for this application'}
```

This Concourse resource checks if the Auth0 resources for a webapp are already there before trying to create them. But for some reason it seems like for some application this check doesn't find the existing resource and therefore tries to re-create it. This causes the Auth0 API to respond with a `400 BAD REQUEST`.

### Possible causes
- bad/intermittent response from Auth0 APIs: This would be strange as I would expect logic to raise an exception sooner than when it tries to create a new `Permission`, [e.g. with a `KeyError` of some sort](https://github.com/ministryofjustice/analytics-platform-concourse-auth0-client-resource/blob/master/moj_analytics/auth0_client.py#L107). Nevertheless I'm adding `request`s `#raise_for_status()` as it's better to fail earlier if that is, strangely, the case.
- ~Bug in [`API.get()` logic](https://github.com/ministryofjustice/analytics-platform-concourse-auth0-client-resource/blob/master/moj_analytics/auth0_client.py#L101-L117)~: This was inspected and it doesn't seem to have any obvious problem.
- ~weird case in repository or app name~: This doesn't seem the case as one of the apps with the problem appear to have a perfectly normal case.
- ~Pagination~: First thought was that the list of existing resources was paginate (this is used to determine if resource exists). This doesn't seem to be the case, or at least not in our case with <200 resources

### 504 error
When raising exceptions on non-2xx response we see the following error coming from the Auth0 Authorization API:

```
504 Server Error: Gateway Timeout for url: https://example.webtask.io/.../api/permissions
```

Related to ticket: https://trello.com/c/I2GozO5D

### CODE REVIEW

**Comment by ntoll** [comment]
Hi folks... I've updated this PR as discussed yesterday:

* We check and raise on the status of the HTTP response.
* All errors are logged using `structlog`.

You can see this working with the following fragment in the Python REPL:

```
>>> from moj_analytics.auth0_client import API
>>> a = API("https://ntoll.org/")
>>> a.request("GET", "foo")
{"event": "Calling endpoint: https://ntoll.org/foo", "timestamp": "2020-04-30T08:14:15.037145Z"}
{"event": "Auth0 API error.", "timestamp": "2020-04-30T08:14:15.242930Z", "exception": "Traceback (most recent call last):\n  File \"/home/ntoll/src/moj/analytics-platform-concourse-auth0-client-resource/moj_analytics/auth0_client.py\", line 91, in request\n    response.raise_for_status()\n  File \"/home/ntoll/.virtualenvs/moj3/lib/python3.8/site-packages/requests/models.py\", line 940, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://ntoll.org/foo"}
```

As you can see, it logs the exception and helpful stack trace. Each log entry is on a single line as JSON, making it easy for log aggregation tools to parse and then present such logs in a human readable manner. This is in the "spirit" of the 12 factor app [style of development](https://12factor.net/logs).

Like I said yesterday, this is a straw-man solution for folks to explore and critique. I expect I'll be asked to change things, which I'm more than happy to do..! Looking forward to your feedback..! :-)
```

**Comment by ntoll** [comment]
Something like [GreyLog](https://www.graylog.org/products/open-source) or others [listed here](https://stackify.com/best-log-management-tools/) might be useful for parsing, storing, analysing and working with such logs. Thoughts please..! :+1:

**Comment by ntoll** [comment]
@aldo addressed your comments with my latest push. Great stuff, and many thanks for the feedback. Exactly what I was looking for. :+1:

**Comment by xoen** [comment]
I'd approve this but I technically created the PR and GitHub doesn't give me the option.

@Mohammad-Tari or @ntoll can probably approve.

We tested this in [the `aldo-test` pipeline](https://concourse.services.alpha.mojanalytics.xyz/teams/main/pipelines/aldo-test/jobs/deploy/builds/19) and it works as expected.

We can then create a release (`v2.0.1`) which will trigger the docker build in quay.io (see badge in README of this repo)...but I'm looking at the place where this custom resource is referenced at the moment.

**Review by ntoll — APPROVED** [review]

**Review by davidread — APPROVED** [review]

**Pull request merged**
